version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: konnect
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "orgdb"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - "5433:5432"
