// Package log provides context-aware and structured logging capabilities.
package log

import (
	"context"
	"encoding/json"
	"net/http"
	"os"
	"strings"

	"github.com/google/uuid"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"go.uber.org/zap/zaptest/observer"
)

var _logger Logger

// Logger is a logger that supports log levels, context and structured logging.
type Logger interface {
	// With returns a logger based off the root logger and decorates it with the given context and arguments.
	With(ctx context.Context, args ...interface{}) Logger

	// Debug uses fmt.Sprint to construct and log a message at DEBUG level
	Debug(args ...interface{})
	// Info uses fmt.Sprint to construct and log a message at INFO level
	Info(args ...interface{})
	// Warn uses fmt.Sprint to construct and log a message at WARN level
	Warn(args ...interface{})
	// Error uses fmt.Sprint to construct and log a message at ERROR level
	Error(args ...interface{})

	// Debugf uses fmt.Sprintf to construct and log a message at DEBUG level
	Debugf(format string, args ...interface{})
	// Infof uses fmt.Sprintf to construct and log a message at INFO level
	Infof(format string, args ...interface{})
	// Warnf uses fmt.Sprintf to construct and log a message at WARN level
	Warnf(format string, args ...interface{})
	// Errorf uses fmt.Sprintf to construct and log a message at ERROR level
	Errorf(format string, args ...interface{})
	Json(v interface{})
}

type logger struct {
	*zap.SugaredLogger
}

type ContextKey int

const (
	RequestIDKey ContextKey = iota
	CorrelationIDKey
)

func GetLogger() Logger {
	if _logger == nil {
		_logger = New()
	}
	return _logger
}

// With is a convenience function that calls GetLogger().With()
func With(ctx context.Context, args ...interface{}) Logger {
	return GetLogger().With(ctx, args...)
}

// New creates a new logger using the default configuration.
func New() Logger {
	return NewWithLevel(getLogLevelFromEnv())
}

// NewWithLevel creates a new logger with the specified log level.
func NewWithLevel(level zapcore.Level) Logger {
	config := zap.NewProductionConfig()
	config.Level = zap.NewAtomicLevelAt(level)

	// For development/debug, use a more readable format
	if level == zapcore.DebugLevel {
		config = zap.NewDevelopmentConfig()
		config.Level = zap.NewAtomicLevelAt(level)
	}

	l, _ := config.Build()
	return NewWithZap(l)
}

// getLogLevelFromEnv reads the LOG_LEVEL environment variable and returns the corresponding zapcore.Level
//
// Log levels are hierarchical - each level includes all levels above it in severity:
//
// debug: Shows ALL logs (debug, info, warn, error, fatal, panic) - Most verbose
// info:  Shows info, warn, error, fatal, panic (excludes debug) - Default level
// warn:  Shows warn, error, fatal, panic (excludes debug, info)
// error: Shows error, fatal, panic (excludes debug, info, warn)
// fatal: Shows fatal, panic only (excludes debug, info, warn, error)
// panic: Shows panic only (excludes all others) - Least verbose
//
// Example usage:
// LOG_LEVEL=debug   # See everything including detailed debugging
// LOG_LEVEL=info    # Production default - informational messages and above
func getLogLevelFromEnv() zapcore.Level {
	logLevel := strings.ToLower(os.Getenv("LOG_LEVEL"))

	switch logLevel {
	case "debug":
		return zapcore.DebugLevel // Shows: debug, info, warn, error, fatal, panic
	case "info":
		return zapcore.InfoLevel // Shows: info, warn, error, fatal, panic
	case "warn", "warning":
		return zapcore.WarnLevel // Shows: warn, error, fatal, panic
	case "error":
		return zapcore.ErrorLevel // Shows: error, fatal, panic
	case "fatal":
		return zapcore.FatalLevel // Shows: fatal, panic
	case "panic":
		return zapcore.PanicLevel // Shows: panic only
	default:
		// Default to info level if not specified or invalid
		return zapcore.InfoLevel // Shows: info, warn, error, fatal, panic
	}
}

// NewWithZap creates a new logger using the preconfigured zap logger.
func NewWithZap(l *zap.Logger) Logger {
	return &logger{l.Sugar()}
}

// NewForTest returns a new logger and the corresponding observed logs which can be used in unit tests to verify log entries.
func NewForTest() (Logger, *observer.ObservedLogs) {
	core, recorded := observer.New(zapcore.InfoLevel)
	return NewWithZap(zap.New(core)), recorded
}

// With returns a logger based off the root logger and decorates it with the given context and arguments.
//
// If the context contains request ID and/or correlation ID information (recorded via WithRequestID()
// and WithCorrelationID()), they will be added to every log message generated by the new logger.
//
// The arguments should be specified as a sequence of name, value pairs with names being strings.
// The arguments will also be added to every log message generated by the logger.
func (l *logger) With(ctx context.Context, args ...interface{}) Logger {
	if ctx != nil {
		if id, ok := ctx.Value(RequestIDKey).(string); ok {
			args = append(args, zap.String("request_id", id))
		}
		if id, ok := ctx.Value(CorrelationIDKey).(string); ok {
			args = append(args, zap.String("correlation_id", id))
		}
	}
	if len(args) > 0 {
		return &logger{l.SugaredLogger.With(args...)}
	}
	return l
}

func (l *logger) Json(v interface{}) {
	if jsonBytes, err := json.MarshalIndent(v, "", "\t"); err != nil {
		l.Errorf("Failed to parse JSON " + err.Error())
	} else {
		l.Info(string(jsonBytes))
	}
}

// WithRequest returns a context which knows the request ID and correlation ID in the given request.
func WithRequest(ctx context.Context, req *http.Request) context.Context {
	id := getRequestID(req)
	if id == "" {
		id = uuid.New().String()
	}
	ctx = context.WithValue(ctx, RequestIDKey, id)
	if id := getCorrelationID(req); id != "" {
		ctx = context.WithValue(ctx, CorrelationIDKey, id)
	}
	return ctx
}

// GetRequestID takes in a context and returns requestID if present or an empty string
// this is improve type safety when extracting values from context
func GetRequestID(ctx context.Context) string {
	if requestID := ctx.Value(RequestIDKey); requestID != nil {
		return requestID.(string)
	}
	return ""
}

// getCorrelationID extracts the correlation ID from the HTTP request
func getCorrelationID(req *http.Request) string {
	return req.Header.Get("X-Correlation-ID")
}

// getRequestID extracts the request ID from the HTTP request
func getRequestID(req *http.Request) string {
	return req.Header.Get("X-Request-ID")
}
