basePath: /v1
definitions:
  forms.CreateServiceForm:
    properties:
      description:
        maxLength: 1000
        minLength: 10
        type: string
      name:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - description
    - name
    type: object
  forms.CreateServiceVersionForm:
    properties:
      description:
        maxLength: 1000
        minLength: 10
        type: string
      releaseTimestamp:
        type: string
      version:
        type: string
    required:
    - description
    - version
    type: object
  forms.UpdateServiceVersionForm:
    properties:
      description:
        maxLength: 1000
        minLength: 10
        type: string
      releaseTimestamp:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      details: {}
      message:
        type: string
      traceId:
        type: string
      type:
        type: string
    type: object
  models.PaginatedResult-models_Service:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Service'
        type: array
      meta:
        properties:
          currentPage:
            type: integer
          nextPage:
            type: integer
          totalCount:
            type: integer
          totalPages:
            type: integer
        type: object
    type: object
  models.PaginatedResult-models_ServiceVersion:
    properties:
      data:
        items:
          $ref: '#/definitions/models.ServiceVersion'
        type: array
      meta:
        properties:
          currentPage:
            type: integer
          nextPage:
            type: integer
          totalCount:
            type: integer
          totalPages:
            type: integer
        type: object
    type: object
  models.Service:
    properties:
      createdAt:
        description: |-
          gorm:"<-:create" only allows create and read but not update
          this is avoid updating created_at with a zero value by mistake
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  models.ServiceVersion:
    properties:
      createdAt:
        description: |-
          gorm:"<-:create" only allows create and read but not update
          this is avoid updating created_at with a zero value by mistake
        type: string
      description:
        type: string
      id:
        type: string
      releaseTimestamp:
        type: string
      serviceId:
        type: string
      updatedAt:
        type: string
      version:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:9000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API server for the Konnect Platform
  termsOfService: http://swagger.io/terms/
  title: Konnect
  version: "1.0"
paths:
  /services:
    get:
      consumes:
      - application/json
      description: Gets all the services available
      parameters:
      - description: Service name, supports searching the passed string in the name
          of the service
        in: query
        name: q
        type: string
      - description: Sort order for the list of services. Accepted values are asc
          and desc. Default is desc(assumes default on invalid values as well)
        in: query
        name: sort
        type: string
      - description: The field on which sorting to be applied, supports name, created_at,
          updated_at. Default is updated_at(assumes default on invalid values as well)
        in: query
        name: sort_by
        type: string
      - description: Page number for pagination (0-based). Default is 0
        in: query
        name: page
        type: integer
      - description: Number of items per page. Default is 10, max is 100
        in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginatedResult-models_Service'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get All services
      tags:
      - Service
    post:
      consumes:
      - application/json
      description: Creates a service
      parameters:
      - description: Service
        in: body
        name: service
        required: true
        schema:
          $ref: '#/definitions/forms.CreateServiceForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Service'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a service
      tags:
      - Service
  /services/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes the specified service
      parameters:
      - description: Service ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete a service
      tags:
      - Service
    get:
      consumes:
      - application/json
      description: Gets the specified service
      parameters:
      - description: Service ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Service'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a service
      tags:
      - Service
    put:
      consumes:
      - application/json
      description: Updates the specified service
      parameters:
      - description: Service ID
        in: path
        name: id
        required: true
        type: string
      - description: Service
        in: body
        name: service
        required: true
        schema:
          $ref: '#/definitions/forms.CreateServiceForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Service'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update a service
      tags:
      - Service
  /services/{serviceId}/versions:
    get:
      consumes:
      - application/json
      description: Gets all the versions available for the specified service
      parameters:
      - description: 'version, supports searching with version prefix, for example:
          passing 1 would return versions like 1.0.1,1.1.4 etc, passing 1.0 would
          return 1.0.3,1.0.7 etc'
        in: query
        name: q
        type: string
      - description: Sort order for the list of service versions. Accepted values
          are asc and desc. Default is desc(assumes default on invalid values as well)
        in: query
        name: sort
        type: string
      - description: The field on which sorting to be applied, supports version, created_at,
          updated_at. Default is updated_at(assumes default on invalid values as well)
        in: query
        name: sort_by
        type: string
      - description: Page number for pagination (0-based). Default is 0
        in: query
        name: page
        type: integer
      - description: Number of items per page. Default is 10, max is 100
        in: query
        name: per_page
        type: integer
      - description: Service ID
        in: path
        name: serviceId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginatedResult-models_ServiceVersion'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get All versions of a service
      tags:
      - ServiceVersion
    post:
      consumes:
      - application/json
      description: |-
        Creates a version for the specified service
        version value must be a semantic version and releaseTimestamp must be valid RFC3339 timestamp
      parameters:
      - description: Service ID
        in: path
        name: serviceId
        required: true
        type: string
      - description: ServiceVersion
        in: body
        name: serviceVersion
        required: true
        schema:
          $ref: '#/definitions/forms.CreateServiceVersionForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ServiceVersion'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a version for a service
      tags:
      - ServiceVersion
  /services/{serviceId}/versions/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes the specified version of a service
      parameters:
      - description: Service ID
        in: path
        name: serviceId
        required: true
        type: string
      - description: Service Version ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete a version for a service
      tags:
      - ServiceVersion
    get:
      consumes:
      - application/json
      description: Get particular version by id for the specified service
      parameters:
      - description: Service ID
        in: path
        name: serviceId
        required: true
        type: string
      - description: Service Version ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ServiceVersion'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a version of a service
      tags:
      - ServiceVersion
    patch:
      consumes:
      - application/json
      description: Updates the specified version of a service, version tag cannot
        be updated
      parameters:
      - description: Service ID
        in: path
        name: serviceId
        required: true
        type: string
      - description: Service Version ID
        in: path
        name: id
        required: true
        type: string
      - description: ServiceVersion
        in: body
        name: serviceVersion
        required: true
        schema:
          $ref: '#/definitions/forms.UpdateServiceVersionForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ServiceVersion'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update a version for a service
      tags:
      - ServiceVersion
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
